main: com.blackout.aow.main.Main
name: AgeOfWar
version: 0.1
api-version: 1.13
author: Blackoutburst
description: Age of War plugin
depend: [NPCAPI]
depend: [HoloAPI]
commands:
  setplayer1:
    description: Set the player 1
    usage: /setplayer1 player
  setplayer2:
    description: Set the player 2
    usage: /setplayer2 player
  start:
    description: Start the game
    usage: /start